@startuml

scale 1280 width
skinparam monochrome true
skinparam defaultFontName "PT Sans"

[*] -> Open : Sender creates a channel
Open -> Settled : Initiated by Receiver
Open -> Settling : Sender starts the settling
Settling -> Settled : Receiver finishes that
Settled -> [*] : Close the channel


@enduml